version: '3.9'

services:

    php-env: 
      container_name: php_container
      build: ./
      volumes:
        - ./src:/var/www/html
      ports:
        - 9000:80

    mysql_db:
      container_name: mysql_container
      image: mysql:latest

     # command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
       # - MYSQL_DATABASE= my_db
        #- MYSQL_USER=db_user
        - MYSQL_ROOT_PASSWORD= ""

    phpmyadmin:
      container_name: phpmyadmin_container
      image: phpmyadmin:latest
      restart: always
      ports:
        - 9001:80
      environment:
        - PMA_ARBITRARY=1

